### ISSUE TITLE
Idea: dark/light toggle 

### ISSUE THREAD

**Issue by SimpleDIY** [andersnoren/norrsken#1]
A toggle to switch between dark and light mode would be great. Thanks for all the great free themes!

**Comment by andersnoren** [comment]
@SimpleDIY Thanks for the suggestion! I don't have any current plans to add a dark/light switcher to Norrsken, but the [Dark Mode Toggle Block](https://wordpress.org/plugins/dark-mode-toggle-block/) by @richtabor should do the trick.
