### ISSUE TITLE
"Select Category“ field too short for German language

### ISSUE THREAD

**Issue by SimpleDIY** [andersnoren/norrsken#2]
The "Select Category" field is a bit too small when using the theme on a German Wordpress blog. The translated text "Select Category" = "Kategorie auswählen" is then cut off in an unattractive way. It might be a good idea to make the field a little wider by default.

**Comment by andersnoren** [comment]
@SimpleDIY I've updated this in 1.0.8, which is out now. Let me know if it does the trick.
