### ISSUE TITLE
Just a question : lightbox

### ISSUE THREAD

**Issue by AceDenghar** [andersnoren/norrsken#3]
Hi,

This is not a real issue but... In your demo for this theme, picture are shown via a lightbox for the post about your [weekend hike above the treeline](weekend-hike-above-the-treeline/).

Wich plugin do you use ? Because it's perfectly clean ˆˆ

Thank you very much.

(And sorry for my English)

**Comment by andersnoren** [comment]
@AceDenghar No worries! I believe that's added by Jetpack.
