### ISSUE TITLE
audio control like the background separator

### ISSUE THREAD

**Issue by differentieel** [andersnoren/norrsken#4]
with many thanks for the beautiful norrsken theme i like to ask a incorporation of the "audio control" in the "single" template
the audio control is the centre of my website - more then 500 tracks are on [ferrie.audio](https://ferrie.audio) - and it would be very nice to have the background separator as a background of the "audio control"

because i like not to ruin the design i ask your kindness to incorporate this background into a template - or tell me how to do it myself without disturbing the design

we found the following code which may do the trick:

`{
background-image: var( --wp--preset--gradient--aurora-horizontal-fade );
border: none;
height: 1px;
}`

found in the separator.css - height would better be a percentage to function in all formats

purpose is to use this CSS to all existing audio controls in the norrsken theme

**Comment by andersnoren** [comment]
@differentieel I'm glad you like it! The aurora background gradients are registered as gradients in the theme, so they can be applied to any element that supports having a background gradient set in the WordPress Site Editor. Unfortunately, it isn't possible to style the HTML element directly in the Site Editor, so you'll have to use custom CSS.

The audio HTML element is rendered differently in pretty much every browser and pretty tricky to style with CSS, but you can find some instructions [here](https://blog.shahednasser.com/how-to-style-an-audio-element/). I don't have any plans on including a custom style for the audio element in Norrsken, so you'll have to add your own in the Custom CSS field in the Site Editor or in a child theme.
